Repository Cubed-Development/Modern-Warfare-Cubed, pull requests merged in 2024-12, with the labels that each got.

#543 Remove the XML config file
  src/main/resources/mwc.cfg
Labels: Optimization, Productivity

#544 Cleanup Vehicles (Lombokify Part 2)
  src/main/java/com/paneedah/mwc/asm/Interceptors.java
  src/main/java/com/paneedah/weaponlib/HighIQSpawnEgg.java
  src/main/java/com/paneedah/weaponlib/LightExposure.java
  src/main/java/com/paneedah/weaponlib/MagazineReloadAspect.java
  src/main/java/com/paneedah/weaponlib/Tuple.java
  src/main/java/com/paneedah/weaponlib/WeaponRenderer.java
  src/main/java/com/paneedah/weaponlib/animation/DebugPositioner.java
  src/main/java/com/paneedah/weaponlib/render/scopes/Reticle.java
  src/main/java/com/paneedah/weaponlib/vehicle/EntityVehicle.java
  src/main/java/com/paneedah/weaponlib/vehicle/jimphysics/InterpolationKit.java
  src/main/java/com/paneedah/weaponlib/vehicle/jimphysics/MechanicalClutch.java
  src/main/java/com/paneedah/weaponlib/vehicle/jimphysics/PhysicsConfiguration.java
  src/main/java/com/paneedah/weaponlib/vehicle/jimphysics/TerrainEvaluator.java
  src/main/java/com/paneedah/weaponlib/vehicle/jimphysics/Transmission.java
  src/main/java/com/paneedah/weaponlib/vehicle/jimphysics/TyreSize.java
  src/main/java/com/paneedah/weaponlib/vehicle/jimphysics/engines/FlywheelSolver.java
  src/main/java/com/paneedah/weaponlib/vehicle/jimphysics/solver/SuspensionBox.java
  src/main/java/com/paneedah/weaponlib/vehicle/jimphysics/solver/SuspensionSolver.java
  src/main/java/com/paneedah/weaponlib/vehicle/jimphysics/solver/VehiclePhysicsSolver.java
  src/main/java/com/paneedah/weaponlib/vehicle/jimphysics/stability/InertialStabilizer.java
  src/main/java/com/paneedah/weaponlib/vehicle/network/VehicleDataContainer.java
  src/main/java/com/paneedah/weaponlib/vehicle/smoothlib/AnimationVector.java
  src/main/java/com/paneedah/weaponlib/vehicle/smoothlib/Mu.java
  src/main/java/com/paneedah/weaponlib/vehicle/smoothlib/PTIVal.java
  src/main/java/com/paneedah/weaponlib/vehicle/smoothlib/QPTI.java
  src/main/java/com/paneedah/weaponlib/vehicle/smoothlib/VehicleRFCam.java
Labels: Productivity

#540 Some minor GUI fixes
  Changelog.md
  src/main/java/com/paneedah/weaponlib/crafting/ammopress/GUIContainerAmmoPress.java
  src/main/java/com/paneedah/weaponlib/crafting/base/GUIContainerStation.java
  src/main/java/com/paneedah/weaponlib/crafting/workbench/GUIContainerWorkbench.java
  src/main/java/com/paneedah/weaponlib/render/ModificationGUI.java
  src/main/java/com/paneedah/weaponlib/render/gui/ColorPalette.java
Labels: Enhancement, Productivity

#541 Overhaul GroovyScript
  Changelog.md
  src/main/java/com/paneedah/mwc/groovyscript/MWCGroovyPlugin.java
  src/main/java/com/paneedah/mwc/groovyscript/MWCLinkGenerator.java
  src/main/java/com/paneedah/mwc/groovyscript/recipes/GSCrafting.java
  src/main/java/com/paneedah/mwc/groovyscript/recipes/GSCraftingRecipe.java
  src/main/java/com/paneedah/mwc/groovyscript/script/CraftingStation.java
  src/main/java/com/paneedah/mwc/items/equipment/carryable/ItemCarryable.java
  src/main/java/com/paneedah/mwc/network/handlers/WorkbenchServerMessageHandler.java
  src/main/java/com/paneedah/weaponlib/CustomArmor.java
  src/main/java/com/paneedah/weaponlib/HighIQSpawnEgg.java
  src/main/java/com/paneedah/weaponlib/ItemAttachment.java
  src/main/java/com/paneedah/weaponlib/ItemVest.java
  src/main/java/com/paneedah/weaponlib/Weapon.java
  src/main/java/com/paneedah/weaponlib/command/MainCommand.java
  src/main/java/com/paneedah/weaponlib/crafting/CraftingRegistry.java
  src/main/java/com/paneedah/weaponlib/crafting/ICraftingRecipe.java
  src/main/java/com/paneedah/weaponlib/crafting/IModernCraftingRecipe.java
  src/main/java/com/paneedah/weaponlib/crafting/ammopress/GUIContainerAmmoPress.java
  src/main/java/com/paneedah/weaponlib/crafting/ammopress/TileEntityAmmoPress.java
  src/main/java/com/paneedah/weaponlib/crafting/base/GUIContainerStation.java
  src/main/java/com/paneedah/weaponlib/crafting/base/TileEntityStation.java
  src/main/java/com/paneedah/weaponlib/crafting/workbench/GUIContainerWorkbench.java
  src/main/java/com/paneedah/weaponlib/crafting/workbench/TileEntityWorkbench.java
  src/main/java/com/paneedah/weaponlib/grenade/ItemGrenade.java
  src/main/resources/assets/mwc/lang/en_US.lang
Labels: Enhancement, Compatibility, Integration, Addition

#531 SIG slx Silencer texture
  Changelog.md
  src/main/java/com/paneedah/mwc/models/Suppressor556x39.java
  src/main/java/com/paneedah/mwc/weapons/Attachments.java
  src/main/resources/assets/mwc/textures/models/sigslxsilencer.png
Labels: Enhancement
